name: breakdb
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pillow
  - python=3
  - pytest
  - pandas
  - pip
  - pip:
    - "--editable=git+https://github.com/pydicom/pydicom.git#egg=pydicom"
